-- To find out the diffference between HOLE DEPTH from Hole Finish Report and LAST SAMPLE DEPTH from Sample Log Report

SELECT 
    H.HOLEID, 
    H.PROJECTCODE, 
    H.DEPTH, 
    MAX(S.SAMPTO) AS MAXSAMPLEDEPTH, 
    CAST(H.STARTDATE AS DATE) AS STARTDATE, 
    CAST(H.ENDDATE AS DATE) AS ENDDATE
FROM 
    HOLELOCATION AS H
INNER JOIN 
    SAMPLE AS S
ON 
    H.HOLEID = S.HOLEID 
    AND H.PROJECTCODE = S.PROJECTCODE
WHERE 
    S.SAMPTO IS NOT NULL
    AND CAST(H.ENDDATE AS DATE) > '2024-01-01'  --<<<<<<< SET THE ENDDATE <<<<<<<--
GROUP BY 
    H.HOLEID, 
    H.PROJECTCODE, 
    H.DEPTH, 
    CAST(H.STARTDATE AS DATE), 
    CAST(H.ENDDATE AS DATE)
HAVING 
    H.DEPTH <> MAX(S.SAMPTO);
