SELECT	dr.DESPATCHNO
		,csa.LABJOBNO
		,csa.SAMPLEID   --Use to show Sample ID
FROM dbo.DESPATCHRETURN AS dr

INNER JOIN dbo.CORPSAMPLEASSAY AS csa
ON csa.LABJOBNO = dr.LABJOBNO

WHERE csa.PRIORITY IN ('1', '2')

GROUP BY
		dr.DESPATCHNO
		,csa.LABJOBNO
		,csa.SAMPLEID   --Use to show Sample ID
HAVING COUNT(DISTINCT csa.PRIORITY) > 1;